name: ntlm
description: Library for making HTTP requests that require NTLM authentication
version: 1.0.3
homepage: https://github.com/mrbbot/ntlm
author: MrBBot <me@mrbbot.co.uk>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  utf: ^0.9.0
  pointycastle: ^1.0.0
  fixnum: ^0.10.0

dev_dependencies:
  test: any
