name: ntlm
description: Library for making HTTP requests that require NTLM authentication
version: 2.0.1
homepage: https://github.com/mrbbot/ntlm

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  pointycastle: ^3.0.1
  fixnum: ^1.0.0

dev_dependencies:
  http_parser: ^4.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
